In [1]:
import numpy as np

In [3]:
data1 = [6,7.5,8,0,1]
data1

[6, 7.5, 8, 0, 1]

In [10]:
# numpy를 이용하여 1차원 배열로 변경하기

arr1 = np.array(data1)
print(arr1,arr1.dtype) ## numpy 는 숫자, 문자 같이 넣을 수 없다. 다 문자로 바뀌거나 함

[6.  7.5 8.  0.  1. ] float64


In [12]:
# 배열의 크기 확인
arr1.shape # 5개의 행이 쭉 있다. 기본적으로 2차원을 쓰기 때문에 콤마가 있음

(5,)

In [19]:
# 2차원 List
data2 = [
            [1,2,3,4],
            [5,6,7,8]
        ]
data2

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [21]:
# numpy 로 2차원 배열로 변형하기
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [40]:
# 0으로 구성된 1차원 배열 생성
np.zeros([3,5,2],dtype='int32') # page, row, column

array([[[0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0]]], dtype=int32)

In [42]:
# 1로만 구성된 배열생성
np.ones(5)

array([1., 1., 1., 1., 1.])

In [46]:
np.full([2,3],10)

array([[10, 10, 10],
       [10, 10, 10]])

In [48]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [49]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [52]:
# 숫자 8로 구성된 3행 5열 배열 생성
np.full((3,5),8)

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

In [63]:
# 범위가 있는 배열 생성
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [64]:
arr1.dtype

dtype('float64')

In [70]:
arr3 = np.array([1,2,3,4,5], dtype=np.int64)
arr3.dtype
arr3

array([1, 2, 3, 4, 5])

In [72]:
# data type을 변경
float_arr1 = arr3.astype('float64')
float_arr1

array([1., 2., 3., 4., 5.])

In [79]:
# 연산
arr1 = np.array((
                [1,2,3],
                [4,5,6]
                ),dtype = np.float64) 
arr1

array([[1., 2., 3.],
       [4., 5., 6.]])

In [81]:
arr2 = np.array([
                [7,8,9],
                [10,11,12]
                ], dtype=np.float64
)
arr2

array([[ 7.,  8.,  9.],
       [10., 11., 12.]])

In [83]:
arr1 + arr2 

array([[ 8., 10., 12.],
       [14., 16., 18.]])

In [84]:
arr1 - arr2

array([[-6., -6., -6.],
       [-6., -6., -6.]])

In [85]:
arr1 * arr2

array([[ 7., 16., 27.],
       [40., 55., 72.]])

In [86]:
arr1 / arr2

array([[0.14285714, 0.25      , 0.33333333],
       [0.4       , 0.45454545, 0.5       ]])

In [88]:
arr1 * 2

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

In [90]:
arr3 = 1 / arr1
arr3

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [93]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [94]:
arr[5]

5

In [96]:
arr[5:9]

array([5, 6, 7, 8])

In [98]:
arr[5:9] = 12 # 걍 리스트는 [5:9] = [12] 이런식으로 해야됨 np.array 는 문법이 다르네
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

In [99]:
arr[:5]

array([0, 1, 2, 3, 4])

In [100]:
arr[8:]

array([12,  9])

## 2차원 배열 

In [147]:
arr2d = np.array([
            [1,2,3,4],
            [5,6,7,8],
            [9,10,11,12],
            [13,14,15,16]
])
arr2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [108]:
arr2d.dtype

dtype('int64')

In [121]:
# 2번 행의 자료 출력
print(arr2d[2,:])


[ 9 10 11 12]


In [131]:
# 1에서 2번행의 자료 출력
print(arr2d[1:2])


[[5 6 7 8]]


In [134]:
# 3번 열의 자료 출력
print(arr2d[:,3:4])

[[ 4]
 [ 8]
 [12]
 [16]]


In [141]:
# 0, 1열의 자료 출력
print(arr2d[:,:2])

[[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]]


In [140]:
# 1행 2열의 자료 출력
print(arr2d[1,2])
print(arr2d[1,2:3] == arr2d[1:2,2])

7
[ True]


In [143]:
arr2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [148]:
arr2d[:2,1:3] = 0
arr2d

array([[ 1,  0,  0,  4],
       [ 5,  0,  0,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])


---
# 난수 발생
- rand : 0부터 1사이의 균일 분포
- randn : 가우시안 표준 정규 분포
- randint : 균일 분포의 정수 난수

## Boolean Indexing
ex(df[df.age > 10])

In [246]:
names = np.array(["Charles","Kenny","Hayoung","Charles","Hayoung","Kenny","Kenny"])
data = np.random.randn(7,4) # 7행,4열

In [247]:
names

array(['Charles', 'Kenny', 'Hayoung', 'Charles', 'Hayoung', 'Kenny',
       'Kenny'], dtype='<U7')

In [248]:
names.shape

(7,)

In [249]:
data

array([[ 0.75305094,  0.53099394, -0.59240622, -0.47173873],
       [-1.58944563,  1.36782645,  1.52677803,  0.18412847],
       [ 0.82336967, -1.1272354 , -1.73188565,  0.27099019],
       [ 0.00420789, -0.06316372, -1.48218946, -0.25145004],
       [ 0.73528723,  0.91107171,  1.38413371,  0.10376939],
       [ 2.04546393,  0.27378116,  0.24844325,  0.20731167],
       [-0.75281768,  0.92828171, -0.25478713, -1.04258628]])

In [250]:
data.shape

(7, 4)

In [251]:
# Mask를 이용한 추출
names == "Charles"

array([ True, False, False,  True, False, False, False])

In [252]:
data[names == "Charles",:] # Boolean indexing 을 이용

array([[ 0.75305094,  0.53099394, -0.59240622, -0.47173873],
       [ 0.00420789, -0.06316372, -1.48218946, -0.25145004]])

In [253]:
data[(names == "Charles")| (names == "Kenny"), :]

array([[ 0.75305094,  0.53099394, -0.59240622, -0.47173873],
       [-1.58944563,  1.36782645,  1.52677803,  0.18412847],
       [ 0.00420789, -0.06316372, -1.48218946, -0.25145004],
       [ 2.04546393,  0.27378116,  0.24844325,  0.20731167],
       [-0.75281768,  0.92828171, -0.25478713, -1.04258628]])

In [254]:
data[:]

array([[ 0.75305094,  0.53099394, -0.59240622, -0.47173873],
       [-1.58944563,  1.36782645,  1.52677803,  0.18412847],
       [ 0.82336967, -1.1272354 , -1.73188565,  0.27099019],
       [ 0.00420789, -0.06316372, -1.48218946, -0.25145004],
       [ 0.73528723,  0.91107171,  1.38413371,  0.10376939],
       [ 2.04546393,  0.27378116,  0.24844325,  0.20731167],
       [-0.75281768,  0.92828171, -0.25478713, -1.04258628]])

In [255]:
data[:,3]

array([-0.47173873,  0.18412847,  0.27099019, -0.25145004,  0.10376939,
        0.20731167, -1.04258628])

In [256]:
# data의 4번째 열 값 중 0보디 작은 것의 mask만들기

data[data[:,3] < 0 , :]

array([[ 0.75305094,  0.53099394, -0.59240622, -0.47173873],
       [ 0.00420789, -0.06316372, -1.48218946, -0.25145004],
       [-0.75281768,  0.92828171, -0.25478713, -1.04258628]])

In [257]:
# data의 4번째 열의 값이 0보다 작은 data들을 0으로 대체하기
data[data[:,3] < 0 , 3] = 0

In [259]:
data

array([[ 0.75305094,  0.53099394, -0.59240622,  0.        ],
       [-1.58944563,  1.36782645,  1.52677803,  0.18412847],
       [ 0.82336967, -1.1272354 , -1.73188565,  0.27099019],
       [ 0.00420789, -0.06316372, -1.48218946,  0.        ],
       [ 0.73528723,  0.91107171,  1.38413371,  0.10376939],
       [ 2.04546393,  0.27378116,  0.24844325,  0.20731167],
       [-0.75281768,  0.92828171, -0.25478713,  0.        ]])

In [258]:
data[data[:,3] <= 0 , :]

array([[ 0.75305094,  0.53099394, -0.59240622,  0.        ],
       [ 0.00420789, -0.06316372, -1.48218946,  0.        ],
       [-0.75281768,  0.92828171, -0.25478713,  0.        ]])

In [278]:
data[(data[:,[1,3]][:,0] <=0) & (data[:,[1,3]][:,1] <=0 ),:]

array([[ 0.00420789, -0.06316372, -1.48218946,  0.        ]])

In [279]:
# 정렬 
arr = np.random.rand(8)
arr

array([0.17774781, 0.60805246, 0.07900426, 0.38818367, 0.29833108,
       0.77799064, 0.49636958, 0.94646988])

In [280]:
# 오름차순 정렬
np.sort(arr)

array([0.07900426, 0.17774781, 0.29833108, 0.38818367, 0.49636958,
       0.60805246, 0.77799064, 0.94646988])

In [281]:
# 내림차순 정렬
np.sort(arr)[::-1]

array([0.94646988, 0.77799064, 0.60805246, 0.49636958, 0.38818367,
       0.29833108, 0.17774781, 0.07900426])

In [283]:
arr = np.random.rand(5,3)
arr

array([[4.81136424e-01, 4.13953186e-01, 3.26805734e-01],
       [3.48468202e-01, 5.95743160e-01, 3.95170807e-01],
       [1.83538935e-01, 3.66519692e-01, 8.50943947e-01],
       [5.59490982e-01, 4.15714599e-01, 9.79461419e-01],
       [1.40248164e-01, 4.32704056e-04, 9.72508994e-01]])

In [285]:
np.sort(arr,axis=0) # 0 : 열방향

array([[1.40248164e-01, 4.32704056e-04, 3.26805734e-01],
       [1.83538935e-01, 3.66519692e-01, 3.95170807e-01],
       [3.48468202e-01, 4.13953186e-01, 8.50943947e-01],
       [4.81136424e-01, 4.15714599e-01, 9.72508994e-01],
       [5.59490982e-01, 5.95743160e-01, 9.79461419e-01]])

In [287]:
np.sort(arr,axis=1) # 1 : 행방향

array([[3.26805734e-01, 4.13953186e-01, 4.81136424e-01],
       [3.48468202e-01, 3.95170807e-01, 5.95743160e-01],
       [1.83538935e-01, 3.66519692e-01, 8.50943947e-01],
       [4.15714599e-01, 5.59490982e-01, 9.79461419e-01],
       [4.32704056e-04, 1.40248164e-01, 9.72508994e-01]])

In [313]:
np.sort(arr, axis=1)[:,::-1]  # 행방향 내림차순

array([[4.81136424e-01, 4.13953186e-01, 3.26805734e-01],
       [5.95743160e-01, 3.95170807e-01, 3.48468202e-01],
       [8.50943947e-01, 3.66519692e-01, 1.83538935e-01],
       [9.79461419e-01, 5.59490982e-01, 4.15714599e-01],
       [9.72508994e-01, 1.40248164e-01, 4.32704056e-04]])

In [314]:
# 중복제거
np.unique(names)

array(['Charles', 'Hayoung', 'Kenny'], dtype='<U7')

---
# reshape

In [317]:
arr = np.arange(1,9)
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [318]:
arr.shape

(8,)

In [323]:
# 2차원 배열로 변경
arr1 = arr.reshape(2,4)
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [324]:
arr2 = arr.reshape(2,2,2) # (page,row,column)
arr2

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [328]:
# 2차원 배열을 1차원으로 변경
arr3 = arr1.reshape(-1,1) # -1 은 값은 1개로 한정되지만 모를 떄 
arr3

#arr1.reshape(-1) 은 1차원이고 (-1,1) 은 2차원이다. 이미지에서는 RGB 1개라도  

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [332]:
arr4 = arr2.reshape(-1)
arr4

array([1, 2, 3, 4, 5, 6, 7, 8])

In [337]:
arr5 = arr2.reshape(-1,1,1)

In [333]:
arr3 == arr4

array([[ True, False, False, False, False, False, False, False],
       [False,  True, False, False, False, False, False, False],
       [False, False,  True, False, False, False, False, False],
       [False, False, False,  True, False, False, False, False],
       [False, False, False, False,  True, False, False, False],
       [False, False, False, False, False,  True, False, False],
       [False, False, False, False, False, False,  True, False],
       [False, False, False, False, False, False, False,  True]])

In [340]:
arr3 * arr4

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 2,  4,  6,  8, 10, 12, 14, 16],
       [ 3,  6,  9, 12, 15, 18, 21, 24],
       [ 4,  8, 12, 16, 20, 24, 28, 32],
       [ 5, 10, 15, 20, 25, 30, 35, 40],
       [ 6, 12, 18, 24, 30, 36, 42, 48],
       [ 7, 14, 21, 28, 35, 42, 49, 56],
       [ 8, 16, 24, 32, 40, 48, 56, 64]])

---
## 낙서장

In [67]:
temp= np.zeros([3,3])
for i in range(len(temp)):
    temp[i,i] = 1
temp



array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])