In [1]:
import numpy as np

In [2]:
np1 = np.array([1,2,3])
np1

array([1, 2, 3])

In [6]:
np2=np.arange(2,10.3)
np2[:]

array([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [21]:
np.zeros((3,2), dtype='float64')

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [24]:
np.array([1,2,3.2])
np.array([1,2,3.2]).dtype

dtype('float64')

In [27]:
np.ones([3,2], dtype= 'int32')
np.ones((3,2), dtype= 'int32').shape

(3, 2)

In [40]:
array1 = np.arange(10)
print('array1:\n',array1)

array2 = array1.reshape(2,5)
print('array2:\n',array2)

array3 = array1.reshape(5,2)
print('array3:\n',array3)

array3 = array1.reshape(10,1)
print('array3:\n',array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
array3:
 [[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [43]:
array2 = array1.reshape(-1,5) ## 마이너스에 의미는 ,나머지 숫자에 맞게 알아서 입력해라라는 의미
print('array2:\n',array2)
array3 = array1.reshape(5,-1)
print('array3:\n',array3)

array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
