In [2]:
import pandas as pd
data = pd.read_csv("../Data/gpascore.csv")
data.head()

admit    gre   gpa  rank
0      0  380.0  3.21     3
1      1  660.0  3.67     3
2      1  800.0  4.00     1
3      1  640.0  3.19     4
4      0  520.0  2.33     4

admit : 합격여부  
gre : 영어성적  
gpa : 학점  
rank : 지원한 대학원 수준  

### Preprocessing(전처리)

In [3]:
# 결측치 처리
data.isnull().sum()


admit    0
gre      1
gpa      0
rank     0
dtype: int64

In [9]:
# 결측치 데이터 삭제
data.dropna(inplace=True)
# 결측치 데이터를 다른값으로 대체
# data.fillna(100)

In [10]:
data.isnull().sum()


admit    0
gre      0
gpa      0
rank     0
dtype: int64

In [12]:
# rank의 종류 파악
data['rank'].value_counts()

2    158
3    129
4     71
1     67
Name: rank, dtype: int64

In [15]:
# 영어 점수의 최소값과 최대값
print('최대값 :', data['gre'].max())
print('최소값 :', data['gre'].min())

최대값 : 800.0
최소값 : 220.0


In [19]:
# Training Data
x = data[['gre','gpa','rank']]
x.head()

gre   gpa  rank
0  380.0  3.21     3
1  660.0  3.67     3
2  800.0  4.00     1
3  640.0  3.19     4
4  520.0  2.33     4

In [20]:
# target Data
y = data['admit']
y.head()

0    0
1    1
2    1
3    1
4    0
Name: admit, dtype: int64

In [24]:
x.count()

gre     425
gpa     425
rank    425
dtype: int64

In [25]:
# target Data
y = data['admit']
y.head()

0    0
1    1
2    1
3    1
4    0
Name: admit, dtype: int64

---
### Deep Learning Model 만들기

In [26]:
from tensorflow import keras

In [47]:
model = keras.Sequential()
# 1번 째 Hidden Layer : 256 노드 (2의 배수, 임의의 갯수(Hyper Parameter)
# activation = sigmoid, tanh, relu, softmax, leakyRelu
model.add(keras.layers.Dense(256, activation= 'tanh', input_shape= (3,)))# 은닉층 
model.add(keras.layers.Dense(1,activation= 'sigmoid')) # 출력층

In [48]:
# 손실함수
model.compile(loss='binary_crossentropy',optimizer='adam',metrics='accuracy')
# Optimizer : learning rate를 알맞게 조정해줌
# - adam
# - adagrad
# - adadelta
# - rmsprop
# - sgd 경사하강법 ,
# 나머지들도 다 출발은 경사하강법인데 최저값을 넘어갔다가 돌아오고 이런점이 조금씩 다름
# loss : 손실함수
# - binary_crossentropy : 분류 및 확률 예측
# metrics : 모델의 평가 기준

In [49]:
np.array(x)
np.array(y)

array([0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0,
       1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,

In [51]:
# 학습 시키기
import numpy as np
model.fit(np.array(x),np.array(y),epochs=300)

Epoch 1/300
14/14 [==============================] - 0s 7ms/step - loss: 7.4443 - accuracy: 0.4729
Epoch 2/300
14/14 [==============================] - 0s 5ms/step - loss: 5.5955 - accuracy: 0.4729
Epoch 3/300
14/14 [==============================] - 0s 6ms/step - loss: 3.7019 - accuracy: 0.4729
Epoch 4/300
14/14 [==============================] - 0s 5ms/step - loss: 1.9202 - accuracy: 0.4729
Epoch 5/300
14/14 [==============================] - 0s 6ms/step - loss: 0.7820 - accuracy: 0.4659
Epoch 6/300
14/14 [==============================] - 0s 6ms/step - loss: 0.7456 - accuracy: 0.5271
Epoch 7/300
14/14 [==============================] - 0s 5ms/step - loss: 0.6954 - accuracy: 0.5271
Epoch 8/300
14/14 [==============================] - 0s 6ms/step - loss: 0.6989 - accuracy: 0.4776
Epoch 9/300
14/14 [==============================] - 0s 6ms/step - loss: 0.6947 - accuracy: 0.5129
Epoch 10/300
14/14 [==============================] - 0s 5ms/step - loss: 0.6931 - accuracy: 0.5271
Epoch 11/

In [52]:
# 예측하기

model.predict(
    [
        [700,3.7,1],
        [700,3.7,2],
        [700,3.7,3],
        [700,3.7,4],
    ]
)

1/1 [==============================] - 0s 158ms/step


2022-07-19 17:50:35.446687: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


array([[0.45479923],
       [0.45479923],
       [0.45479923],
       [0.45479923]], dtype=float32)

In [53]:
# 예측하기

model.predict(
    [
        [400,2.2,1],
        [400,2.2,2],
        [400,2.2,3],
        [400,2.2,4],
    ]
)

1/1 [==============================] - 0s 18ms/step


array([[0.4547993 ],
       [0.4547993 ],
       [0.45479923],
       [0.45479923]], dtype=float32)