In [1]:
range(1,11)

range(1, 11)

In [3]:
list(range(1,11))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [5]:
list(range(0,11,2))

[0, 2, 4, 6, 8, 10]

In [7]:
list(range(10,-1,-2))

[10, 8, 6, 4, 2, 0]

In [9]:
list(range(0,10,-2))

[]

In [13]:
print([1,2,3])

[1, 2, 3]


In [14]:
for i in range(1,11):
    print(i)

1
2
3
4
5
6
7
8
9
10


In [15]:
import math

In [20]:
# 1에서 10까지의 제곱근을 출력하기
for i in range(1,11):
    print(i,": %.8f"%math.sqrt(i))


1 : 1.00000000
2 : 1.41421356
3 : 1.73205081
4 : 2.00000000
5 : 2.23606798
6 : 2.44948974
7 : 2.64575131
8 : 2.82842712
9 : 3.00000000
10 : 3.16227766


In [96]:
a = list(range(10,101,10)).extend([1,2,3])
#a.extend([1,2,3])
print(a)


None


In [37]:
### 구구단 9단 출력

i = 9
for j in range(1,10):
    print(i, "X", j, "=", "%2d"%(i*j))


9 X 1 =  9
9 X 2 = 18
9 X 3 = 27
9 X 4 = 36
9 X 5 = 45
9 X 6 = 54
9 X 7 = 63
9 X 8 = 72
9 X 9 = 81


In [47]:
# 구구단 결과만 출력
for i in range(2,10):
    for j in range(1,10):
        print("%2d"%(i*j), end = ' ') # print( )

    print()

 2  4  6  8 10 12 14 16 18 
 3  6  9 12 15 18 21 24 27 
 4  8 12 16 20 24 28 32 36 
 5 10 15 20 25 30 35 40 45 
 6 12 18 24 30 36 42 48 54 
 7 14 21 28 35 42 49 56 63 
 8 16 24 32 40 48 56 64 72 
 9 18 27 36 45 54 63 72 81 


In [51]:
# for 문에 Tuple 사용하기
var = [(1,2), (3,4), (5,6)]

for first, last in var:
    print(first, ":", last)

1 : 2
3 : 4
5 : 6


총 5명의 학생이 시험을 보았는 데, 시험점수가 60점을 넘으면 합격이고  
그렇지 않으면 불합격이다.  
합격, 불합격 보여주기  

In [53]:
scores = [90, 25, 67, 45, 80]

for number in range(len(scores)):
    print("%i의 학생은 합격 입니다."%number) if scores[number] >= 60 else print("%i의 학생은 불합격 입니다."%number)

0의 학생은 합격 입니다.
1의 학생은 불합격 입니다.
2의 학생은 합격 입니다.
3의 학생은 불합격 입니다.
4의 학생은 합격 입니다.


In [58]:
a, b ,c=1,2,3
print(a,b,c)
print([a,b,c])


1 2 3
[1, 2, 3]


In [78]:
for first,second in [{1:2,2:3},{4:5,9:2}.values()]:
    print(first,second)



1 2
5 2


In [85]:
print(range(1,10))
print(list(range(1,103,10)))
print(list(range(2,3)))

range(1, 10)
[1, 11, 21, 31, 41, 51, 61, 71, 81, 91, 101]
[2]


In [99]:
scores = [90, 25, 67, 45, 80]
number = 1

for score in scores:
    print(f"{number}의 학생은 합격입니다.") if score >= 60 else print(f"{number}의 학생은 불합격입니다.")
    number += 1


1의 학생은 합격입니다.
2의 학생은 불합격입니다.
3의 학생은 합격입니다.
4의 학생은 불합격입니다.
5의 학생은 합격입니다.


In [108]:
scores = [90, 25, 67, 45, 80]
number = 1

for score in scores:
    print(f"{number}의 학생은 {score}이므로 합격입니다.") if score >= 60 else print(f"{number}의 학생은 {score}이므로 불합격입니다.")
    number += 1

1의 학생은 90이므로 합격입니다.
2의 학생은 25이므로 불합격입니다.
3의 학생은 67이므로 합격입니다.
4의 학생은 45이므로 불합격입니다.
5의 학생은 80이므로 합격입니다.


학생들 점수의 평균을 구하여 평균점수 보다 낮으면 불합격  
평균점수보다 같거나 높으면 합격을 위의 출력과 같이 보여 주기

In [129]:
import numpy as np

In [134]:
scores = [90, 25, 67, 45, 80]
number = 1

mean = np.mean(scores)

print("학급의 평균은 %.2f입니다.\n"%mean)
for score in scores:
    print(f"{number}의 학생은 {score}이므로 합격입니다.") if score >= mean else print(f"{number}의 학생은 {score}이므로 불합격입니다.")
    number += 1

학급의 평균은 61.40입니다.

1의 학생은 90이므로 합격입니다.
2의 학생은 25이므로 불합격입니다.
3의 학생은 67이므로 합격입니다.
4의 학생은 45이므로 불합격입니다.
5의 학생은 80이므로 합격입니다.


In [149]:
scores = [90, 25, 67, 45, 80]
number = 1

#mean = np.mean(scores)
#print("학급의 평균은 %.2f입니다.\n"%mean)
for score in scores:
    print(f"{number}의 학생은 {score}이므로 합격입니다.") if (score >= mean)  else 1
    number += 1

학급의 평균은 61.40입니다.

1의 학생은 90이므로 합격입니다.
3의 학생은 67이므로 합격입니다.
5의 학생은 80이므로 합격입니다.


총 5명의 학생이 시험을 보앗는 데 시험점수가 60점을 넘으면 합격이고 그렇지 않으면 불합격이.  
합격인 학생들의 번호만 새로운 list를 생성하여 출력하기

In [208]:
scores = [90, 25, 67, 45, 80]
number = 1

mean = np.mean(scores)
print("학급의 평균은 %.2f입니다.\n"%mean)
list01 = []
print('합격자 번호 \n','-'*9 , sep = '' )
for score in scores:
    list01.append(number), print('{0:^9}'.format(list01[number-1])) if (score >= mean)  else 1
    number += 1


학급의 평균은 61.40입니다.

합격자 번호 
---------
    1    
    3    
    5    


---
# 문장과 단어 추출

In [210]:
string = """나는 홍길동 입니다.
주소는 서울시 입니다.
나이는 35세 입니다."""

In [213]:
string

'나는 홍길동 입니다.\n주소는 서울시 입니다.\n나이는 35세 입니다.'

In [217]:
# 문단 -> 문장
sents = [] # 문장 저장
words = [] # 단어 저장
for sen in string.split("\n"):
    sents.append(sen)
    words.extend(sen.split(" "))

print(sents)
print(words)

['나는 홍길동 입니다.', '주소는 서울시 입니다.', '나이는 35세 입니다.']
['나는', '홍길동', '입니다.', '주소는', '서울시', '입니다.', '나이는', '35세', '입니다.']


In [221]:
var01 = [1,2,3,4]
var02 = []
# var02에 var01의 인덱스 번호에 각각 5를 곱하여 출력하기
for i in var01:
    var02.append(i*5)
    
var02

[5, 10, 15, 20]

# 파이썬의 listed for문

In [222]:
var01 = [1,2,3,4]
var02 = [i*5 for i in var01]
var02

[5, 10, 15, 20]

In [252]:
# var01의 데이터가 짝수 인 경우에만 5를 곱하여 var02 list 만들기
var01 = [1,2,3,4]
var02 = [i*5 if not(i%2) else i for i in var01]
var02

[1, 10, 3, 20]

In [250]:
## 구구단 결과만 리스트로 만들기
list03 = [ i*j for j in range(2,10) for i in range(1,10)]
list03

[2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 3,
 6,
 9,
 12,
 15,
 18,
 21,
 24,
 27,
 4,
 8,
 12,
 16,
 20,
 24,
 28,
 32,
 36,
 5,
 10,
 15,
 20,
 25,
 30,
 35,
 40,
 45,
 6,
 12,
 18,
 24,
 30,
 36,
 42,
 48,
 54,
 7,
 14,
 21,
 28,
 35,
 42,
 49,
 56,
 63,
 8,
 16,
 24,
 32,
 40,
 48,
 56,
 64,
 72,
 9,
 18,
 27,
 36,
 45,
 54,
 63,
 72,
 81]

In [259]:
# 60점 이상의 학생 점수만 List로 만들어서 평균 출력하기 (listed for문 사용)
scores = [90,25,67,45,80]
list04 = [score for score in scores if score>= 60]
print(sum(list04)/len(list04))

79.0


---
## 여기서 부턴 수업외 낙서장 

In [205]:
num = 5
print('{:>10}'.format(1))
print('{:<10}'.format(1))
print('{:^10}'.format(1))


         1
1         
    1     


In [137]:
np1= np.array([1,2,3])
display(np1)

array([1, 2, 3])

In [164]:
np.zeros((2,3))
np.full((2,3),5)
np.eye(5)
np.dot(np.eye(5)*2,np.full((5,5),2) )


array([[4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.]])

In [167]:
np.divide(np.eye(5)*2,np.full((5,5),5))

array([[0.4, 0. , 0. , 0. , 0. ],
       [0. , 0.4, 0. , 0. , 0. ],
       [0. , 0. , 0.4, 0. , 0. ],
       [0. , 0. , 0. , 0.4, 0. ],
       [0. , 0. , 0. , 0. , 0.4]])

In [169]:
np.sum(np.eye(6))

6.0

In [123]:
a= list(range(ord(chr(0x01)),ord('z')+1)) + list(range(ord('A'),ord('Z')+1))
"".join(chr(i) for i in a)


'\x01\x02\x03\x04\x05\x06\x07\x08\t\n\x0b\x0c\r\x0e\x0f\x10\x11\x12\x13\x14\x15\x16\x17\x18\x19\x1a\x1b\x1c\x1d\x1e\x1f !"#$%&\'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ'

In [114]:
print(chr(0x41))

A
