# numpy 내장함수

In [3]:
import numpy as np

In [4]:
# 평균
np.mean(range(1, 11))


5.5

In [6]:
# 합계
np.sum(range(1,11))

55

In [7]:
# 분산
np.var(range(1,11))

8.25

In [8]:
# 표준편차
np.std(range(1,11))

2.8722813232690143

In [23]:
# 분산의 제곱근이 표준편차
print(np.sqrt(np.var(range(1,11))) == np.std(range(1,11)))
print(np.sqrt(np.var(range(1,11))) is np.std(range(1,11)))
print( 1== 1.00)
print( 1 is 1.00)

True
False
True
False


<>:5: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:5: SyntaxWarning: "is" with a literal. Did you mean "=="?
/var/folders/r9/905wglgd76v1f_n1q9jw68rr0000gn/T/ipykernel_4461/2556132494.py:5: SyntaxWarning: "is" with a literal. Did you mean "=="?
  print( 1 is 1.00)


In [13]:
# 최대값
np.max(range(1,11))

10

In [14]:
# 최소값
np.min(range(1,11))

1

In [15]:
# 중앙값
np.median(range(1,11))

5.5

In [33]:
# 누적합
list(np.cumsum(range(1,11)))

[1, 3, 6, 10, 15, 21, 28, 36, 45, 55]

In [40]:
# 누적합의 결과만 보기
print(list(np.cumsum(range(1,11)))[-1])
list(np.cumsum(range(1,11))).pop()

55


55

In [44]:
# 누적곱
np.cumprod(range(1,11))[-1]

3628800

---
# 사용자 정의 함수

In [45]:
def hiF():
    return 'Hi'

In [47]:
var = hiF()
print(var)

Hi


In [56]:
def test2(x, y):
    
    return x + y

In [57]:
test2(2,3)

5

In [58]:
# 함수에 입력되는 인수가 몇개일지 모를 경우

def sumManyF(*inputValue):
    sum = 0
    for i in inputValue:
        sum += i
    return sum

In [60]:
sumManyF(1,2,3,4,5,6,7,8,9,10)

55

In [65]:
# 여러개의 숫자를 받아 최대값과 최소값의 차이를 구하는 함수 만들기
def sumManyF2(*nums):
    print(type(nums))
    return np.max(nums) - np.min(nums)
sumManyF2(1,3,5,7,9)

<class 'tuple'>


8

In [72]:
def gugu(x,y):
    for i in x:
        for j in y:
            print(f"{i} X {j} = {i*j}")
        print('-' *20)

In [73]:
# 구구단에서 단과 곱해지는 수를 리스트로 입력하여 출력하기
x = list(range(2,9,3))
y = list(range(6,10))
gugu(x,y)


2 X 6 = 12
2 X 7 = 14
2 X 8 = 16
2 X 9 = 18
--------------------
5 X 6 = 30
5 X 7 = 35
5 X 8 = 40
5 X 9 = 45
--------------------
8 X 6 = 48
8 X 7 = 56
8 X 8 = 64
8 X 9 = 72
--------------------


In [122]:
# 덧셈 기능과 곱셈기능을 구분하여 숫자의 결과를 보여주는 함수
def sum_mulF(*vars1):
    return np.sum(vars1[1:]) if((vars1[0] == 'sum') ) else np.cumprod(vars1[1:])[-1] if (vars1[0] == 'mul') else '연산자를 잘못입력했습니다.'

In [123]:
result = sum_mulF('sum', 1,2,3,4,5)
print(result)
result = sum_mulF('mul', 1,2,3,4,5)
print(result)
result = sum_mulF('add', 1,2,3,4,5)
print(result)

15
120
연산자를 잘못입력했습니다.


In [ ]:
# return 문의 결과값은 항상 하나이다.


In [131]:
def sum_mul(a,b):
    return a + b, a * b

In [132]:
return_sum , return_mul =  sum_mul(3,4)
print(return_sum)
print(return_mul)

7
12


In [135]:
# 함수의 초기값 설정하기
def sum_mul(a,b = 10):
    return (a+b,a*b)


In [139]:
# b = 10 <- 가장 많이 쓰는 숫자
print(sum_mul(10))
print(sum_mul(10,20))

(20, 100)
(30, 200)


---
# 람다(lambda) 함수
- 보통 함수를 한 줄로 간결하게 만들 떄 사용
- return 명령어가 필요없다.



In [141]:
def addFunction(a,b):
    return a + b

In [142]:
addFunction(10,20)

30

In [146]:
addLambda = lambda a, b : a + b
addLambda(10,20)

30

In [147]:
funx = lambda *a : sum(a)
funx(1,2,4,4,4,4,4,4,4

31

In [120]:
print(np.cumproduct([1,2,3,4,5]))
print(np.cumprod([1,2,3,4,5]))
np.cumproduct([1,2,3])


[  1   2   6  24 120]
[  1   2   6  24 120]


array([1, 2, 6])

In [110]:

str01 = "123a45abcde"

str02 = [i if(i == "a") else 'b' for i in str01 if(i != '1')]
"".join(i for i in str02)



'bbabbabbbb'